wheel_track:
   front: 0.515
   rear: 0.515
wheelbase: 0.392
wheel_radius:
   front: 0.1325
   rear: 0.1325
wheel_width:
   front: 0.1
   rear: 0.1
hub_carrier_offset:
   front: 0.
   rear: 0.
aabb :
   length: 0.54000
   width: 0.40000
   height: 0.18000
   center: [0., 0., 0.188]
mass: 170.
mass_center_position: [0., 0., 0.188]
ground_clearance: 0.098
