base_footprint_joint_name : base_footprint
inertial_joint_name: inertial_joint
front_left_wheel_spinning_joint_name: front_left_wheel_spinning_joint
front_right_wheel_spinning_joint_name: front_right_wheel_spinning_joint
rear_left_wheel_spinning_joint_name: rear_left_wheel_spinning_joint
rear_right_wheel_spinning_joint_name: rear_right_wheel_spinning_joint
